#!/bin/sh

rm -rf build
mkdir build

DEST=$PWD/build

# This and its friend the ruby script delete_bin
# are horribly coded. Fix. Now. Before it breaks.

for dir in $PWD/*
do
  test -d "$dir" || continue

  cd $dir
  echo "Building contents of $dir"
  go build
  cd ..

  for bin in $dir/*
  do
          cp $bin $DEST
  done

done

for bin in build/*.go
do
        rm $bin
done

./delete_bin
