#!/bin/sh

rm -rf build
mkdir build

DEST=$PWD/build
echo "Compiling coreutils..."

# This and its friend the ruby script delete_bin
# are horribly coded. Fix. Now. Before it breaks.

for dir in $PWD/*
do
  test -d "$dir" ||  continue

  if [ $dir != $DEST ]
  then
          cd $dir
          go build
          cd ..

          for bin in $dir/*
          do
                  cp $bin $DEST
          done
  fi

done

for bin in build/*.go
do
        rm $bin
done

echo "Cleaning up..."
./delete_bin
